<a href="https://colab.research.google.com/github/raj-vijay/dl/blob/master/01_Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor**

In mathematics, a tensor is an algebraic object that describes a (multilinear) relationship between sets of algebraic objects related to a vector space.

Tensors can take several different forms – for example: scalars and vectors (which are the simplest tensors), dual vectors, multi-linear maps between vector spaces, and even some operations such as the dot product. Tensors are defined independent of any basis, although they are often referred to by their components in a basis related to a particular coordinate system. 

- Generalization of vectors and matrices
- Collection of numbers
- Specific shapes

**Tensor Flow**

Open-source library for graph-based numerical computation
- Developed by the Google Brain Team

Low and high level APIs
- Addition, multiplication, differentiation
- Machine learning models

Important changes in TensorFlow 2.0
- Eager execution by default
- Model building with Keras and Estimators

**Defining Tensors in Tensor Flow**

In [0]:
# Import Tensor Flow
import tensorflow as tf

In [0]:
# 0D Tensor
d0 = tf.ones((1,))

In [0]:
# 1D Tensor
d1 = tf.ones((2,))

In [0]:
# 2D Tensor
d2 = tf.ones((2, 2))

In [0]:
# 3D Tensor
d3 = tf.ones((2, 2, 2))

In [0]:
# Print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


**Constants in Tensor Flow**

A constant is the simplest category of tensor
- Not trainable
- Can have any dimension

In [0]:
from tensorflow import constant
# Define a 2x3 constant.
a = constant(3, shape=[2, 3])

# Define a 2x2 constant.
b = constant([1, 2, 3, 4], shape=[2, 2])

In [0]:
print("a =", a.numpy(), "\nb =", b.numpy())

a = [[3 3 3]
 [3 3 3]] 
b = [[1 2]
 [3 4]]


**Defining and initializing variables**

Note: Unlike a constant, a variable's value can be modified. This will be quite useful when we want to train a model by updating its parameters. Constants can't be used for this purpose, so variables are the natural choice.

In [0]:
import tensorflow as tf
# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

# Define a constant
b = tf.constant(2, tf.float32)

In [0]:
# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0*b

In [0]:
print("c0 =", c0.numpy(), "\nc1 =", c1.numpy())

c0 = [ 2.  4.  6.  8. 10. 12.] 
c1 = [ 2.  4.  6.  8. 10. 12.]


**Tensorflow Operations**

Tensorflow has a model of computation that leverages graphs.

Tensorflow graph contains edges and nodes, with edges as tensors and nodes as operations.

![alt text](https://raw.githubusercontent.com/raj-vijay/dl/master/images/Tensorflow%20Opeations.jpg)

The **add()** operation performs element-wise addition with two tensors

Element-wise addition requires both tensors to have the same shape

In [0]:
#Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

# Define 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

In [0]:
# Perform tensor addition with add()

C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

Element-wise multiplication performed using **multiply()** operation.

The tensors multiplied must have the same shape.

In [0]:
# Import operators from tensorflow
from tensorflow import ones, matmul, multiply

# Define tensors
A0 = ones(1)
A31 = ones([3, 1])
A34 = ones([3, 4])
A43 = ones([4, 3])

The **reduce_sum()** operator sums over the dimensions of a tensor

reduce_sum(A) sums over all dimensions of A

reduce_sum(A, i) sums over dimension i

In [0]:
# Import operations from tensorflow
from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
A = ones([2, 3, 4])

**Performing element-wise multiplication**

Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors. An example of an element-wise multiplication, denoted by the ⊙ symbol

In [0]:
# Import operations from tensorflow
from tensorflow import ones_like, multiply, constant

# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like(A1)
B23 = ones_like(A23)

# Perform element-wise multiplication
C1 = multiply(A1, B1) 
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


**Making predictions with matrix multiplication**

The matrix of input data, features, contains two columns: education level and age. The target vector, bill, is the size of the credit card borrower's bill.

In [0]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]
