<a href="https://colab.research.google.com/github/raj-vijay/dl/blob/master/02_First_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Build a neural network**

Keras library are used to create neural networks and to train these neural networks to classify images. 

These models will all be of the Sequential type, meaning that the outputs of one layer are provided as inputs only to the next layer.

Here, we create a neural network with Dense layers, meaning that each unit in each layer is connected to all of the units in the previous layer. 

For example, each unit in the first layer is connected to all of the pixels in the input images. The Dense layer object receives as arguments the number of units in that layer, and the activation function for the units. For the first layer in the network, it also receives an input_shape keyword argument.

In [0]:
# Import fundamental libraries used for the tensorflow
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [0]:
# Load the Fashion MNIST Data from TensorFlow Keras
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [0]:
# Shape of data
print("Train Images: ", train_images.shape)
print("Test Images: ", test_images.shape)

Train Images:  (60000, 28, 28)
Test Images:  (10000, 28, 28)


In [0]:
# Imports components from Keras
from keras.models import Sequential
from keras.layers import Dense

# Initializes a sequential model
model = Sequential()

# First layer
model.add(Dense(100, activation='relu', input_shape=(784,)))

# Second layer
model.add(Dense(100, activation='relu'))

# Output layer
model.add(Dense(10, activation='softmax'))

**Compile a neural network**

Once we have constructed a model in Keras, the model needs to be compiled before it can be fit to data. 

This means that you need to specify the optimizer that will be used to fit the model and the loss function that will be used in optimization. 

Optionally, a list of metrics can be specified that the model will keep track of. 

For example, if you want to know the classification accuracy, provide the list ['accuracy'] to the metrics keyword argument.

In [0]:
# Compile the model
model.compile(optimizer='adam', 
           loss='categorical_crossentropy', 
           metrics=['accuracy'])

**Fitting a neural network model to clothing data**

Here, we fit the fully connected neural network constructed in the previous section to image data. 

The training data is provided as two variables: train_data that contains the pixel data for 60000 images of the ten clothing classes and train_labels, which contains the labels for each one of these 60000 images. 

Transform the data into the network's expected input and then fit the model on training data and training labels.


In [0]:
# Reshape the data to two-dimensional array
train_images = train_images.reshape(train_images.shape[0], 784)


**One-Hot Encoding for Training Labels**

In [0]:
# The number of image categories
n_categories = 10

# The unique values of categories in the data
categories = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Initialize ohe_labels as all zeros
ohe_labels = np.zeros((len(train_labels), n_categories))

# Loop over the labels
for ii in range(len(train_labels)):
    # Find the location of this label in the categories variable
    jj = np.where(categories == train_labels[ii])
    # Set the corresponding zero to one
    ohe_labels[ii, jj] = 1

In [0]:
print(ohe_labels)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
# Fit the model
model.fit(train_images, ohe_labels, validation_split=0.2, epochs=3)

Train on 48000 samples, validate on 12000 samples
Epoch 1/3
48000/48000 [==============================] - 4s 80us/step - loss: 2.8024 - accuracy: 0.7203 - val_loss: 0.8426 - val_accuracy: 0.7487
Epoch 2/3
48000/48000 [==============================] - 4s 78us/step - loss: 0.7360 - accuracy: 0.7668 - val_loss: 0.6500 - val_accuracy: 0.7877
Epoch 3/3
48000/48000 [==============================] - 4s 78us/step - loss: 0.6076 - accuracy: 0.7977 - val_loss: 0.5679 - val_accuracy: 0.8067


**One-Hot Encoding for Test Labels**

In [0]:
# The number of image categories
n_categories = 10

# The unique values of categories in the data
categories = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Initialize ohe_labels as all zeros
ohe_test_labels = np.zeros((len(test_labels), n_categories))

# Loop over the labels
for ii in range(len(test_labels)):
    # Find the location of this label in the categories variable
    jj = np.where(categories == test_labels[ii])
    # Set the corresponding zero to one
    ohe_test_labels[ii, jj] = 1

In [0]:
print(ohe_test_labels)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


**Cross-validation for neural network evaluation**

To evaluate the model, a separate test data-set is used. 

As in the train data, the images in the test data also need to be reshaped before they can be provided to the fully-connected network because the network expects one column per pixel in the input.

In [0]:
# Reshape test data
test_images = test_images.reshape(test_images.shape[0], 784)

# Evaluate the model
model.evaluate(test_images, ohe_test_labels)

10000/10000 [==============================] - 0s 25us/step


[0.5972538591861725, 0.803600013256073]